// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZXfFailqYhzxnaQQm5vJoOW89vKxoxXY',
    appId: '1:567866060220:web:4434d0e8787bcdfd108fb9',
    messagingSenderId: '567866060220',
    projectId: 'grocerwe-ba4d7',
    authDomain: 'grocerwe-ba4d7.firebaseapp.com',
    databaseURL: 'https://grocerwe-ba4d7-default-rtdb.firebaseio.com',
    storageBucket: 'grocerwe-ba4d7.appspot.com',
    measurementId: 'G-L04994EN4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-KJ7N0s0xhvO09mFoBI1JETDRvhEDgwI',
    appId: '1:567866060220:android:6014529032674cf4108fb9',
    messagingSenderId: '567866060220',
    projectId: 'grocerwe-ba4d7',
    databaseURL: 'https://grocerwe-ba4d7-default-rtdb.firebaseio.com',
    storageBucket: 'grocerwe-ba4d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh2gMEktm7imgL32TvG-tKEnTLxSmt7uQ',
    appId: '1:567866060220:ios:d15d38c749018b65108fb9',
    messagingSenderId: '567866060220',
    projectId: 'grocerwe-ba4d7',
    databaseURL: 'https://grocerwe-ba4d7-default-rtdb.firebaseio.com',
    storageBucket: 'grocerwe-ba4d7.appspot.com',
    iosBundleId: 'com.example.grocerwe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh2gMEktm7imgL32TvG-tKEnTLxSmt7uQ',
    appId: '1:567866060220:ios:d15d38c749018b65108fb9',
    messagingSenderId: '567866060220',
    projectId: 'grocerwe-ba4d7',
    databaseURL: 'https://grocerwe-ba4d7-default-rtdb.firebaseio.com',
    storageBucket: 'grocerwe-ba4d7.appspot.com',
    iosBundleId: 'com.example.grocerwe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZXfFailqYhzxnaQQm5vJoOW89vKxoxXY',
    appId: '1:567866060220:web:291b84186a1a0c01108fb9',
    messagingSenderId: '567866060220',
    projectId: 'grocerwe-ba4d7',
    authDomain: 'grocerwe-ba4d7.firebaseapp.com',
    databaseURL: 'https://grocerwe-ba4d7-default-rtdb.firebaseio.com',
    storageBucket: 'grocerwe-ba4d7.appspot.com',
    measurementId: 'G-MNG9NV9B68',
  );
}
